version: "3.2"

services:
  backend:
    build: ./
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "8080:80"
    #   - "20051:8081"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "0.5"
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
